export const FiltersActionTypes = {
    SET_SIDEBAR_FILTERS: 'SET_SIDEBAR_FILTERS',
    TOGGLE_SIDEBAR_DROPPED: 'TOGGLE_SIDEBAR_DROPPED',
    SET_SEARCHBAR_FILTERS: 'SET_SEARCHBAR_FILTERS',
    SET_SORTBAR_VALUE: 'SET_SORTBAR_VALUE'
}